/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellVendorsRouteImport } from './routes/_shell.vendors'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellScorecardRouteImport } from './routes/_shell.scorecard'
import { Route as ShellRiskRouteImport } from './routes/_shell.risk'
import { Route as ShellReportsRouteImport } from './routes/_shell.reports'
import { Route as ShellPresentationRouteImport } from './routes/_shell.presentation'
import { Route as ShellNegotiationRouteImport } from './routes/_shell.negotiation'
import { Route as ShellKpisRouteImport } from './routes/_shell.kpis'
import { Route as ShellDecisionMatrixRouteImport } from './routes/_shell.decision-matrix'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellComparisonRouteImport } from './routes/_shell.comparison'
import { Route as ShellCategoriesRouteImport } from './routes/_shell.categories'
import { Route as ShellAnalyticsRouteImport } from './routes/_shell.analytics'
import { Route as ShellVendorsIdRouteImport } from './routes/_shell.vendors.$id'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellVendorsRoute = ShellVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellScorecardRoute = ShellScorecardRouteImport.update({
  id: '/scorecard',
  path: '/scorecard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellRiskRoute = ShellRiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => ShellRoute,
} as any)
const ShellReportsRoute = ShellReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPresentationRoute = ShellPresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => ShellRoute,
} as any)
const ShellNegotiationRoute = ShellNegotiationRouteImport.update({
  id: '/negotiation',
  path: '/negotiation',
  getParentRoute: () => ShellRoute,
} as any)
const ShellKpisRoute = ShellKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDecisionMatrixRoute = ShellDecisionMatrixRouteImport.update({
  id: '/decision-matrix',
  path: '/decision-matrix',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellComparisonRoute = ShellComparisonRouteImport.update({
  id: '/comparison',
  path: '/comparison',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCategoriesRoute = ShellCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAnalyticsRoute = ShellAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ShellRoute,
} as any)
const ShellVendorsIdRoute = ShellVendorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShellVendorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/categories': typeof ShellCategoriesRoute
  '/comparison': typeof ShellComparisonRoute
  '/dashboard': typeof ShellDashboardRoute
  '/decision-matrix': typeof ShellDecisionMatrixRoute
  '/kpis': typeof ShellKpisRoute
  '/negotiation': typeof ShellNegotiationRoute
  '/presentation': typeof ShellPresentationRoute
  '/reports': typeof ShellReportsRoute
  '/risk': typeof ShellRiskRoute
  '/scorecard': typeof ShellScorecardRoute
  '/settings': typeof ShellSettingsRoute
  '/vendors': typeof ShellVendorsRouteWithChildren
  '/vendors/$id': typeof ShellVendorsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof ShellAnalyticsRoute
  '/categories': typeof ShellCategoriesRoute
  '/comparison': typeof ShellComparisonRoute
  '/dashboard': typeof ShellDashboardRoute
  '/decision-matrix': typeof ShellDecisionMatrixRoute
  '/kpis': typeof ShellKpisRoute
  '/negotiation': typeof ShellNegotiationRoute
  '/presentation': typeof ShellPresentationRoute
  '/reports': typeof ShellReportsRoute
  '/risk': typeof ShellRiskRoute
  '/scorecard': typeof ShellScorecardRoute
  '/settings': typeof ShellSettingsRoute
  '/vendors': typeof ShellVendorsRouteWithChildren
  '/vendors/$id': typeof ShellVendorsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/analytics': typeof ShellAnalyticsRoute
  '/_shell/categories': typeof ShellCategoriesRoute
  '/_shell/comparison': typeof ShellComparisonRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/decision-matrix': typeof ShellDecisionMatrixRoute
  '/_shell/kpis': typeof ShellKpisRoute
  '/_shell/negotiation': typeof ShellNegotiationRoute
  '/_shell/presentation': typeof ShellPresentationRoute
  '/_shell/reports': typeof ShellReportsRoute
  '/_shell/risk': typeof ShellRiskRoute
  '/_shell/scorecard': typeof ShellScorecardRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/vendors': typeof ShellVendorsRouteWithChildren
  '/_shell/vendors/$id': typeof ShellVendorsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/categories'
    | '/comparison'
    | '/dashboard'
    | '/decision-matrix'
    | '/kpis'
    | '/negotiation'
    | '/presentation'
    | '/reports'
    | '/risk'
    | '/scorecard'
    | '/settings'
    | '/vendors'
    | '/vendors/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/categories'
    | '/comparison'
    | '/dashboard'
    | '/decision-matrix'
    | '/kpis'
    | '/negotiation'
    | '/presentation'
    | '/reports'
    | '/risk'
    | '/scorecard'
    | '/settings'
    | '/vendors'
    | '/vendors/$id'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/analytics'
    | '/_shell/categories'
    | '/_shell/comparison'
    | '/_shell/dashboard'
    | '/_shell/decision-matrix'
    | '/_shell/kpis'
    | '/_shell/negotiation'
    | '/_shell/presentation'
    | '/_shell/reports'
    | '/_shell/risk'
    | '/_shell/scorecard'
    | '/_shell/settings'
    | '/_shell/vendors'
    | '/_shell/vendors/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/vendors': {
      id: '/_shell/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof ShellVendorsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/scorecard': {
      id: '/_shell/scorecard'
      path: '/scorecard'
      fullPath: '/scorecard'
      preLoaderRoute: typeof ShellScorecardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/risk': {
      id: '/_shell/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof ShellRiskRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/reports': {
      id: '/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ShellReportsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/presentation': {
      id: '/_shell/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof ShellPresentationRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/negotiation': {
      id: '/_shell/negotiation'
      path: '/negotiation'
      fullPath: '/negotiation'
      preLoaderRoute: typeof ShellNegotiationRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/kpis': {
      id: '/_shell/kpis'
      path: '/kpis'
      fullPath: '/kpis'
      preLoaderRoute: typeof ShellKpisRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/decision-matrix': {
      id: '/_shell/decision-matrix'
      path: '/decision-matrix'
      fullPath: '/decision-matrix'
      preLoaderRoute: typeof ShellDecisionMatrixRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/comparison': {
      id: '/_shell/comparison'
      path: '/comparison'
      fullPath: '/comparison'
      preLoaderRoute: typeof ShellComparisonRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/categories': {
      id: '/_shell/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof ShellCategoriesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/analytics': {
      id: '/_shell/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ShellAnalyticsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/vendors/$id': {
      id: '/_shell/vendors/$id'
      path: '/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof ShellVendorsIdRouteImport
      parentRoute: typeof ShellVendorsRoute
    }
  }
}

interface ShellVendorsRouteChildren {
  ShellVendorsIdRoute: typeof ShellVendorsIdRoute
}

const ShellVendorsRouteChildren: ShellVendorsRouteChildren = {
  ShellVendorsIdRoute: ShellVendorsIdRoute,
}

const ShellVendorsRouteWithChildren = ShellVendorsRoute._addFileChildren(
  ShellVendorsRouteChildren,
)

interface ShellRouteChildren {
  ShellAnalyticsRoute: typeof ShellAnalyticsRoute
  ShellCategoriesRoute: typeof ShellCategoriesRoute
  ShellComparisonRoute: typeof ShellComparisonRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellDecisionMatrixRoute: typeof ShellDecisionMatrixRoute
  ShellKpisRoute: typeof ShellKpisRoute
  ShellNegotiationRoute: typeof ShellNegotiationRoute
  ShellPresentationRoute: typeof ShellPresentationRoute
  ShellReportsRoute: typeof ShellReportsRoute
  ShellRiskRoute: typeof ShellRiskRoute
  ShellScorecardRoute: typeof ShellScorecardRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellVendorsRoute: typeof ShellVendorsRouteWithChildren
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAnalyticsRoute: ShellAnalyticsRoute,
  ShellCategoriesRoute: ShellCategoriesRoute,
  ShellComparisonRoute: ShellComparisonRoute,
  ShellDashboardRoute: ShellDashboardRoute,
  ShellDecisionMatrixRoute: ShellDecisionMatrixRoute,
  ShellKpisRoute: ShellKpisRoute,
  ShellNegotiationRoute: ShellNegotiationRoute,
  ShellPresentationRoute: ShellPresentationRoute,
  ShellReportsRoute: ShellReportsRoute,
  ShellRiskRoute: ShellRiskRoute,
  ShellScorecardRoute: ShellScorecardRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellVendorsRoute: ShellVendorsRouteWithChildren,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
